import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>
) {
  return <div>{props.children}</div>;
}
