import { Container, Header } from '@/shared/components';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>
) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header
          hasSearch={false}
          hasCart={false}
          className="border-b-gray-200"
        />
        {props.children}
      </Container>
    </main>
  );
}
